import { PipeTransform, Injectable, BadRequestException } from '@nestjs/common';

@Injectable()
export class ParseCuid2Pipe implements PipeTransform<string> {
  transform(value: string): string {
    // CUID2 format: 24-32 lowercase alphanumeric characters
    // M2 R3: Range is 24-32 because @paralleldrive/cuid2 generates 24 chars by default
    // but can be configured (via createId({ length: n })) to use 24-32 chars.
    // This project uses default 24-char IDs, but the pipe accepts 24-32 for flexibility.
    //
    // L5 R3: CUID2 IDs generated by createId() start with 'c' by default, but createId()
    // can be configured to use a different prefix. This regex accepts all lowercase
    // alphanumeric characters for flexibility and future-proofing.
    if (!/^[a-z0-9]{24,32}$/.test(value)) {
      throw new BadRequestException('Ungültiges ID-Format');
    }
    return value;
  }
}
